### ISSUE TITLE
Canvas: trying to use a recycled bitmap

### ISSUE THREAD

**Issue by mikepenz** [mikepenz/wall-splash-android#9]
java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@43180af8
at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1084)
at android.view.GLES20Canvas.drawBitmap(GLES20Canvas.java:844)
at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:496)
at android.view.View.draw(View.java:15379)
at android.view.View.getDisplayList(View.java:14288)
at android.view.View.getDisplayList(View.java:14330)
at android.view.View.draw(View.java:15108)
at android.view.ViewGroup.drawChild(ViewGroup.java:3310)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3147)
at android.view.View.getDisplayList(View.java:14283)
at android.view.View.getDisplayList(View.java:14330)
at android.view.View.draw(View.java:15108)
at android.view.ViewGroup.drawChild(ViewGroup.java:3310)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3147)
at android.view.View.draw(View.java:15397)
at android.widget.FrameLayout.draw(FrameLayout.java:472)
at android.widget.ScrollView.draw(ScrollView.java:2184)
at android.view.View.getDisplayList(View.java:14288)
at android.view.View.getDisplayList(View.java:14330)
at android.view.View.draw(View.java:15108)
at android.view.ViewGroup.drawChild(ViewGroup.java:3310)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3147)
at android.view.View.draw(View.java:15397)
at android.view.View.getDisplayList(View.java:14288)
at android.view.View.getDisplayList(View.java:14330)
at android.view.View.draw(View.java:15108)
at android.view.ViewGroup.drawChild(ViewGroup.java:3310)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3147)
at android.view.View.getDisplayList(View.java:14283)
at android.view.View.getDisplayList(View.java:14330)
at android.view.View.draw(View.java:15108)
at android.view.ViewGroup.drawChild(ViewGroup.java:3310)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3147)
at android.view.View.getDisplayList(View.java:14283)
at android.view.View.getDisplayList(View.java:14330)
at android.view.View.draw(View.java:15108)
at android.view.ViewGroup.drawChild(ViewGroup.java:3310)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3147)
at android.view.View.getDisplayList(View.java:14283)
at android.view.View.getDisplayList(View.java:14330)
at android.view.View.draw(View.java:15108)
at android.view.ViewGroup.drawChild(ViewGroup.java:3310)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3147)
at android.view.View.getDisplayList(View.java:14283)
at android.view.View.getDisplayList(View.java:14330)
at android.view.View.draw(View.java:15108)
at android.view.ViewGroup.drawChild(ViewGroup.java:3310)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3147)
at android.view.View.draw(View.java:15397)
at android.widget.FrameLayout.draw(FrameLayout.java:472)
at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2567)
at android.view.View.getDisplayList(View.java:14288)
at android.view.View.getDisplayList(View.java:14330)
at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1588)
at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1467)
at android.view.ViewRootImpl.draw(ViewRootImpl.java:2754)
at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2620)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2188)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1249)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6585)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:803)
at android.view.Choreographer.doCallbacks(Choreographer.java:603)
at android.view.Choreographer.doFrame(Choreographer.java:573)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:789)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5586)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
at dalvik.system.NativeStart.main(Native Method)

**Comment by mikepenz** [comment]
should be fixed in v1.5.3
